### ISSUE TITLE
it can't work when somebody do  Handstand in the pic

### ISSUE THREAD

**Issue by wxy656** [DenisTome/Lifting-from-the-Deep-release#1]
If the person in the picture is not standing (such as push-ups or inverted), it can not be promoted to 3d.
Will you follow up on this project so that it can support the actions of various scenes?

**Comment by DenisTome** [comment]
Hi,
the probabilistic model that we provide for 3D lifting can be adapted to handle those kind of poses.
The main priority right now is to provide a system working on the main data-sets for 2D and 3D human pose estimation. Some of these, like Leeds (http://www.comp.leeds.ac.uk/mat4saj/lsp.html), have poses where the person is standing upside-down, hence we'll have to update the "3D lifter".
