### ISSUE TITLE
No module named lifting

### ISSUE THREAD

**Issue by saraershadi** [DenisTome/Lifting-from-the-Deep-release#11]
Hi , 
I tried to run your code but it reaches to this error. What is the source of the error ?

Best regards
Sarah
------------------------------------------------------------------------------
sara@sara:~/Downloads/Lifting-from-the-Deep-release-master$ python Applications/Lifting-from-the-Deep/demo.py 
Traceback (most recent call last):
  File "Applications/Lifting-from-the-Deep/demo.py", line 11, in <module>
    from lifting import PoseEstimator
ImportError: No module named lifting

**Comment by DenisTome** [comment]
Hi, yes there was a bug. Thanks! It's fixed now.
Run:
python applications/demo.py

**Comment by Hosseinhashemiir** [comment]
Dear Denis,
I have the same problem, I will be appreciated by you if please guide me to fix this problem? 

> ~/Downloads/Lifting-from-the-Deep-release-master$

 python applications/demo.py
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "applications/demo.py", line 11, in <module>
    from lifting import PoseEstimator
  File "/home/hossein/Downloads/Lifting-from-the-Deep-release-master/packages/lifting/__init__.py", line 1, in <module>
    from ._pose_estimator import *
  File "/home/hossein/Downloads/Lifting-from-the-Deep-release-master/packages/lifting/_pose_estimator.py", line 7, in <module>
    from . import utils
  File "/home/hossein/Downloads/Lifting-from-the-Deep-release-master/packages/lifting/utils/__init__.py", line 10, in <module>
    from .process import *
  File "/home/hossein/Downloads/Lifting-from-the-Deep-release-master/packages/lifting/utils/process.py", line 15, in <module>
    import skimage.transform
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/__init__.py", line 1, in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/hough_transform.py", line 3, in <module>
    from .. import measure
  File "/usr/local/lib/python2.7/dist-packages/skimage/measure/__init__.py", line 1, in <module>
    from ._find_contours import find_contours
ImportError: cannot import name find_contours
>

**Comment by DenisTome** [comment]
this seems to be an error for skimage.
Be sure you have matplotlib (pip install matplotlib), and try to reinstall skimage.

**Comment by Hosseinhashemiir** [comment]
im using : 
scikit-image (0.13.1)
matplotlib (2.1.0)

**Comment by DenisTome** [comment]
The error you get is due to some installation problem of skimage.
If you cannot manage to fix the installation, a solution is to use opencv to perform the same operation.

In the file, Lifting-from-the-Deep-release-master/packages/lifting/utils/process.py
remove "import skimage.transform"
and substitute line 117 with
cv2.resize(np.clip(heatmaps[oid], -1, 1), tuple(size), interpolation=cv2.INTER_CUBIC)

**Comment by Hosseinhashemiir** [comment]
Thanks for your kindly attention. 

right now, I just have this error:

> ~/Downloads/Lifting-from-the-Deep-release-master$ python applications/demo.py
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "applications/demo.py", line 11, in <module>
    from lifting import pose_estimator
ImportError: cannot import name pose_estimator
> 

seems can't find pose_estimator !!!
I'm using python2.7 in ubuntu 16.04.

**Comment by Hosseinhashemiir** [comment]
Thanks for your kindly attention.
is working :+1:
