### ISSUE TITLE
Error when running scripts on cpu 

### ISSUE THREAD

**Issue by yashiro32** [DenisTome/Lifting-from-the-Deep-release#17]
I got this error: "Segmentation fault (core dumped)" when running your scripts on the cpu.

**Comment by GajjarMihir** [comment]
Did you first run the setup.sh file?

**Comment by yashiro32** [comment]
Yes, I ran the setup.sh to download the trained models and to install the external utilities.

The scripts works on tensorflow-gpu but not on tensorflow-cpu and gotten the error I stated previously.

**Comment by yashiro32** [comment]
It's on tensorflow-cpu that is getting the error.

**Comment by DenisTome** [comment]
I've uploaded a faster version that should also require less memory in the GPU. If that it's still not enough, you can try to reduce the batch size in the file config.py which would reduce further the space needed to allocate the graph.

**Comment by MritulaC** [comment]
setup.sh can be run from git bash on windows.

or

Download the  *.tar.tz files manually by pasting the URLs from the setup.sh files and excecute each instruction line by line in git bash.

This is how I overcame the same issue
