### ISSUE TITLE
How to deal with invisible body parts in a picture

### ISSUE THREAD

**Issue by Carlllll** [DenisTome/Lifting-from-the-Deep-release#19]
It works really well with full body people even playing soccer.
Any advises to deal with invisible body parts in a picture(like just upper bodies shown in a frame)??

**Comment by DenisTome** [comment]
The approach is able to retrieve poses with missing joints. It's possible to define which is the minimum number of joints needed for the reconstruction, hence you could play with that parameter depending on the number of joints you need. 
In case the whole lower body is missing, the approach is going to retrieve a meaningful pose only for the upper body, whereas the lower body is going to be an average pose of the poses in the dataset we trained on.

**Comment by Carlllll** [comment]
Thank your so much for your answer.
Let's say that I want to test a pic and there is a person with only the whole upper body in the pic.
What part of your code do I have to change for the test??

**Comment by DenisTome** [comment]
The easiest thing to do, which involves almost not touching at all the code, is to say the all the joints in the lower part of the body are not visible and let the approach reconstruct everything with the rest.
Specifically, in the function detect_parts_from_likelihoods in `utils/process.py` you set 
`visible[oid, pid] = False` for the part id (pid) corresponding to those joints.
Then the last thing you are left to do is about plotting them. Here again you just choose to plot the upper body.
