### ISSUE TITLE
Pose 3D output is centered to origin.

### ISSUE THREAD

**Issue by KelSolaar** [DenisTome/Lifting-from-the-Deep-release#25]
Hi,

I'm testing the project on an image sequence, and while I manage to successfully get poses for the sequence, they are always centered to origin. I tried to initialise a `PoseEstimator` for the whole sequence or one per frame without much differences. Am I missing something obvious?

Cheers,

Thomas

**Comment by DenisTome** [comment]
Hi,

this is due to a normalization that it's applied in the code.

**Comment by Guo-king** [comment]
I have tested the project on a video，and I found that the 3D outputs centered to origin.
Is there some methods to save the problem. Or shall i remove some code to avoid the normalization because I want to reserve the change of skeleton center. @KelSolaar @DenisTome 
THANK YOU!
