### ISSUE TITLE
The speed question

### ISSUE THREAD

**Issue by GreatGBL** [DenisTome/Lifting-from-the-Deep-release#26]
Greeting! I am running the 3D pose by this paper (Lifting from the deep), the 2D human joints are from Oppenpose (https://github.com/ildoonet/tf-pose-estimation)

I test each frame I need approximate 0.05s to process the 2D joints,  while it requires near 10s to transform 3D, so it is impossible to construct real-time system. However, I see the demo in Lifting, it is real-time, how do you do that? And may I ask how to speed up the 3D transform ? Thanks!

**Comment by DenisTome** [comment]
Hi,
Yes I know. In our case we had a cython optimized version of that code that is much more efficient, saving in the cache some matrices for saving time.

**Comment by dandingol03** [comment]
Hi,  can you send me  the link of the cython optimized code
