### ISSUE TITLE
A issue in python demo.py

### ISSUE THREAD

**Issue by Huang9495** [DenisTome/Lifting-from-the-Deep-release#27]
I operate the code `python demo.py` while a issue is occuring. And the issue as fellows:

My environment: python 2.7; GPU:1060 &1080ti; ubuntu16.04

Can you help me?

![screenshot from 2018-09-22 08-13-13](https://user-images.githubusercontent.com/26674689/45910901-bb561c80-be3f-11e8-85c6-6b0c61070386.png)

**Comment by DenisTome** [comment]
Your specs are ok. They should not be the problem
1080ti can definitely handle our model. To further test this, you could reduce the batch size.
To do that, edit the file packages/lifting/utils/config.py setting ```BATCH_SIZE = 1```.

**Comment by Huang9495** [comment]
@DenisTome  OK, I try to do it. Thanks you
