### ISSUE TITLE
I can't run the demo.py.

### ISSUE THREAD

**Issue by Ssrzbao** [DenisTome/Lifting-from-the-Deep-release#30]

**Comment by Ssrzbao** [comment]
A problem has occurred when I run the demo.py.
OutOfRangeError (see above for traceback): Read less bytes than requested
	 [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[{{node save/RestoreV2/_301}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_306_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
I have changed the Batch_Size=1, but the operation is invalid.
My environment is ubuntu16.04 python=2.7 tensorflow=1.11

**Comment by DenisTome** [comment]
you should be able to run it with batch_size 1.

Regardless, that is a range error. Have you checked that there are actually detections?

**Comment by NguyenDangBinh** [comment]
dear Dr,
I am a master student about Mechatronic. 
Can you send me a full code about CNN? I need them for learning.
Thank you so much

**Comment by DenisTome** [comment]
The public code is only what we are going to release so far.

In the future we might provide the whole framework for training the model as well.
