### ISSUE TITLE
Where is the part of lifting 2D belief-maps, projected 2D pose and fusion layer in code?

### ISSUE THREAD

**Issue by HanlunAI** [DenisTome/Lifting-from-the-Deep-release#31]
In my understanding, an input image would go through the PersonNet (to find out position of each person), PoseNet (to get the most confident pixel as the location of each landmark), and Prob3dPose (to calculate the 3D pose). 

In Prob3dPose, the paper introduced steps on lifting 2D belief-maps into 3D, projecting to a new 2D pose belief maps and training weights for 2D fusion. Where can we find codes on this part? 

Please help. Thank you.

**Comment by HanlunAI** [comment]
You also mentioned that these novel layers were implemented as extension of the Convolutional Pose Machines. I guess we can find the codes there.

**Comment by DenisTome** [comment]
That part is not available on the public repository. The repository
contains only the final operations of taking the heat maps and lifting them
in 3d.

**Comment by HanlunAI** [comment]
Thank you!
