### ISSUE TITLE
Error in lifting module

### ISSUE THREAD

**Issue by gangubai** [DenisTome/Lifting-from-the-Deep-release#32]
python3 pt3-webcam3D.py 
Traceback (most recent call last):
  File "pt3-webcam3D.py", line 17, in <module>
    from lifting.prob_model import Prob3dPose
ModuleNotFoundError: No module named 'lifting'

Please can someone help in that??Also I am not able to access the updated version of the repo..If someone have it,can somebody please send it??
Thanks in advance!!

**Comment by DenisTome** [comment]
You should run demo.py from within the applications directory.

**Comment by DenisTome** [comment]
Closing the task due to inactivity
