### ISSUE TITLE
error in drawing.cpp for some images

### ISSUE THREAD

**Issue by edrdos101** [DenisTome/Lifting-from-the-Deep-release#34]
For some images (haven't figured out the correlation) when using `draw_limbs`, terminal throws this error:

```
_COLORS[lid], LIMB_DRAW_SIZE*_NORMALISATION_FACTOR , 16)
cv2.error: OpenCV(4.0.1) /tmp/opencv-20190105-31032-o160to/opencv-4.0.1/modules/imgproc/src/drawing.cpp:1811: error: (-215:Assertion failed) 0 < thickness && thickness <= MAX_THICKNESS in function 'line'
```

There seems to be no logical explanation why plotting works fine for some images while not for others...

**Comment by DenisTome** [comment]
Alright thanks, it's quite weird anyway.
