### ISSUE TITLE
ValueError: cannot reshape array of size 0 into shape (0,newaxis,2)

### ISSUE THREAD

**Issue by MritulaC** [DenisTome/Lifting-from-the-Deep-release#37]
in normalise_data
    d2 = d2.reshape(d2.shape[0], -1, 2).transpose(0, 2, 1)
ValueError: cannot reshape array of size 0 into shape (0,newaxis,2)

Hi,
 I am getting the above error when giving a jpeg image for reconstruction. How am I to overcome this error?#
Thanks,
 Mritula

**Comment by DenisTome** [comment]
That means that for that specific frame there are no predictions.
Probably, by playing with /packages/lifting/utils/config.py VISIBLE_PART, you can find a threshold that is better for your specific images.

**Comment by MritulaC** [comment]
In draw.py in line 43 I replaced "LIMB_DRAW_SIZE*_NORMALISATION_FACTOR" to 5, its working fine now. Thanks

**Comment by MritulaC** [comment]
How to determine the maximum and minimum values for Visible part?

**Comment by DenisTome** [comment]
VISIBLE_PART is a threshold and the way it's used is to say that if hm_value > VISIBLE_PART then it's visible.
If you make that threshold smaller that condition is still False. therefore try to make it larger than 1e-3, not smaller

**Comment by DenisTome** [comment]
Okay that is weird. Just to be sure about it, what happens if you check the content of d2?

The way it's working right now is to have the mean(heatmap) > VISIBLE_PART (https://github.com/DenisTome/Lifting-from-the-Deep-release/blob/d4f8a10a7d6887d83721cd2b24edb05056bb8a68/packages/lifting/utils/process.py#L125)

you could change that to max(heatmap).

**Comment by MritulaC** [comment]
Thanks, I will check it and update you.

**Comment by DenisTome** [comment]
so, what's the content of the variable part_hmap?

**Comment by MritulaC** [comment]
It says 0 in part_hmap

**Comment by MritulaC** [comment]
I have given print statement for part_hmap output, but the program is not priniting out the value
for oid, (yc, xc) in enumerate(centers):
        part_hmap = skimage.transform.resize(
           ..........
        print(part_hmap)

not sure why :-(

**Comment by DenisTome** [comment]
the reason it's not printing anything is probably because it's empty.
One thing you can do is to say:

if len(centers) < 1:
    # skip to next frame
    return None, None, None

**Comment by MritulaC** [comment]
I did that and i got the following
ValueError: too many values to unpack (expected 2)

**Comment by manjuj123** [comment]
Hi, When I run this code, I am also getting ValueError: cannot reshape array of size 0 into shape (0,newaxis,2).

The png file I am using was created using an iOS app. This app creates an image of myself as JPEG. I converted it to a png file using Preview Export option. The program works with the test_image.png.

Can you help me understand what is it that I am missing?

**Comment by DenisTome** [comment]
I've updated the code to catch that error. However in order to fix that, you need to try to change the ```packages/lifting/utils/config.py``` file, specifically CENTER_TR.

**Comment by manjuj123** [comment]
Thanks Denis. What do you suggest I change the CENTER_TR to from 0.4? Why do you suggest that I change it?

**Comment by manjuj123** [comment]
After changing the CENTER_TR to 0.2, I did manage to go past this error and get the output generated. Thanks.

**Comment by DenisTome** [comment]
Perfect.
Yeah, at the end there are 2 thresholds controlling everything and by adjusting them you can control the visibility.

**Comment by MritulaC** [comment]
Thanks, I will try the same and update.
