### ISSUE TITLE
Using posenet for estimating, 2d detections and input it to 3d pose lifter

### ISSUE THREAD

**Issue by timtensor** [DenisTome/Lifting-from-the-Deep-release#39]
Hi , I am currently looking into python implementationo posenet to do 2D pose estimation.  
[posenet-python](https://github.com/rwightman/posenet-python). In it , the following [decode single person](https://github.com/rwightman/posenet-python/blob/master/posenet/decode.py). The following return the  17 keypoints `instance_keypoint_coords`  and pose confidence. `instance_keypoint_scores` . 

Where can we input to get the corresponding 3d estimation ?  

Can it also be extended to videos ?

**Comment by DenisTome** [comment]
I'm not sure I get exactly what you are trying to do.
If by that you mean that you want to use their 2D estimations and this repository to lift them in 3D, then at line 144 of packages/lifting/_pose_estimator.py use can see where the pose + visibility is given to the 3D lifting module.
Just make sure that the format of the pose is the same as the one expected by our approach.
