### ISSUE TITLE
run demo error on win10

### ISSUE THREAD

**Issue by Angel113110** [DenisTome/Lifting-from-the-Deep-release#49]
Dear author
    Thanks for sharing so interesting work. I met an error when I ran demo.py, the error like this:

No visible people in the image. Change CENTER_TR in packages/lifting/utils/config.py ...

But in my picture, there is one person. How this happened？Can you give me some help? Thanks!

**Comment by DenisTome** [comment]
Hi,

In the file ``packages/lifting/utils/config.py`` there are a set of parameters that can be tuned to change the behavior of the model based on different types of images,

Among those, CENTER_TR is the one you are looking at. Changing that value will make the person "visible" to the algorithm. For more detailed info, please refer to [issue 37](https://github.com/DenisTome/Lifting-from-the-Deep-release/issues/37).
