### ISSUE TITLE
can this model run for real-time inference?

### ISSUE THREAD

**Issue by dandingol03** [DenisTome/Lifting-from-the-Deep-release#53]
Hi, thanks for your amazing work! But the model run for real-time maybe a little slow, i just know you have made a cython optimized version code , is the code open or is convenient for you to share the code with a link? Thanks in advance!

**Comment by abdulahad7** [comment]
I would really love to see that too

**Comment by DenisTome** [comment]
we changed it and it's not compatible anymore. Sorry
