### ISSUE TITLE
Unable to run it on videos

### ISSUE THREAD

**Issue by Zumbalamambo** [DenisTome/Lifting-from-the-Deep-release#6]
How do I run it in a realtime video?

**Comment by Zumbalamambo** [comment]
Im getting the following error ```
from prob_model import Prob3dPose
ModuleNotFoundError: No module named 'prob_model'
```

**Comment by DenisTome** [comment]
About running the program on a real time video, our approach has been designed for a single image. Therefore, if you want to run on a video you have to run the pose_estimator.estimate(image) for each of the frames in your video, independently.
About the error, make sure that you are running the demo.py file from inside the project folder using python2.7

**Comment by timtensor** [comment]
Hi, is it possible to convert not real ti,e) but any video into frames and then run `pose_estimator.estimate(image)` and reccombine the  estimated images ?
